import { Injectable } from '@angular/core';
import { Item } from './item';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/173e04de6b294e65b53d6b6cc9048a7d'; // berbeda untuk setiap mahasiswa

  constructor(private http: HttpClient) {}

  getItems() {
    return this.http.get(`${this.baseUrl}/item`);
  }

  getItem(id: number) {
    // /<resource>/<id>
    return this.http.get(`${this.baseUrl}/item/${id}`);
  }

  postItem(item: Item) {
    delete item._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/item`, item);
  }

  updateItem(item: Item) {
    const id = item._id; // we copy the original id
    delete item._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/item/${id}`, item);
  }

  deleteItem(item: Item) {
    const id = item._id; // we copy the original id
    return this.http.delete(`${this.baseUrl}/item/${id}`);
  }
}
